using System.Windows;using System.Windows.Controls;using System.Windows.Data;using MessagingServerManager.Core;using MessagingServerManager.Infrastructure;
namespace MessagingServerManager.App;
public sealed class ServerEditorWindow:Window
{
 readonly ServerDefinition server;readonly IReadOnlyList<ServerDefinition> all;readonly PathResolver paths;readonly TextBlock errors=new(){Foreground=System.Windows.Media.Brushes.Firebrick,TextWrapping=TextWrapping.Wrap};
 public ServerEditorWindow(ServerDefinition value,IReadOnlyList<ServerDefinition> definitions,PathResolver resolver){server=value;all=definitions;paths=resolver;DataContext=server;Title=value.Name=="New Server"?"Add Server":"Edit Server";Width=670;Height=760;MinHeight=620;WindowStartupLocation=WindowStartupLocation.CenterOwner;Content=Build();}
 UIElement Build(){var root=new DockPanel{Margin=new Thickness(18)};var buttons=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right};var save=new Button{Content="Save",MinWidth=90,Margin=new Thickness(5),Padding=new Thickness(10,6,10,6)};save.Click+=Save;var cancel=new Button{Content="Cancel",MinWidth=90,Margin=new Thickness(5),Padding=new Thickness(10,6,10,6)};cancel.Click+=(_,_)=>DialogResult=false;buttons.Children.Add(save);buttons.Children.Add(cancel);DockPanel.SetDock(buttons,Dock.Bottom);root.Children.Add(buttons);DockPanel.SetDock(errors,Dock.Bottom);root.Children.Add(errors);var scroll=new ScrollViewer{VerticalScrollBarVisibility=ScrollBarVisibility.Auto};var panel=new StackPanel();scroll.Content=panel;root.Children.Add(scroll);
  Add(panel,"Name",nameof(server.Name));AddCombo(panel,"Server type",nameof(server.ServerType),Enum.GetValues<ServerType>());AddCheck(panel,"Enabled",nameof(server.Enabled));Add(panel,"Executable name or path",nameof(server.Executable));Add(panel,"Working directory",nameof(server.WorkingDirectory));AddCombo(panel,"Launch mode",nameof(server.LaunchMode),Enum.GetValues<LaunchMode>());Add(panel,"Config file path",nameof(server.ConfigFilePath));Add(panel,"Additional arguments",nameof(server.AdditionalArguments),true);Add(panel,"Log file name or path",nameof(server.LogFilePath));Add(panel,"Health-check host",nameof(server.HealthCheckHost));Add(panel,"Health-check port",nameof(server.HealthCheckPort));AddCheck(panel,"Start with application",nameof(server.StartWithApplication));AddCheck(panel,"Auto restart",nameof(server.AutoRestart));Add(panel,"Graceful stop timeout (seconds)",nameof(server.GracefulStopTimeoutSeconds));AddCheck(panel,"Force kill after timeout",nameof(server.ForceKillAfterTimeout));
  var nats=Header("NATS settings");panel.Children.Add(nats);Add(panel,"Server name","Nats.ServerName");Add(panel,"Client port","Nats.ClientPort");Add(panel,"HTTP monitoring port","Nats.MonitoringPort");Add(panel,"Cluster port","Nats.ClusterPort");Add(panel,"Store directory","Nats.StoreDirectory");var rv=Header("TIBCO Rendezvous settings");panel.Children.Add(rv);Add(panel,"Service","TibRv.Service");Add(panel,"Network","TibRv.Network");Add(panel,"Daemon address","TibRv.DaemonAddress");Add(panel,"HTTP administration port","TibRv.HttpAdministrationPort");Add(panel,"Listen port","TibRv.ListenPort");return root;}
 static TextBlock Header(string text)=>new(){Text=text,FontSize=15,FontWeight=FontWeights.SemiBold,Foreground=System.Windows.Media.Brushes.SteelBlue,Margin=new Thickness(0,16,0,6)};
 static void Add(Panel p,string label,string path,bool multi=false){p.Children.Add(new TextBlock{Text=label,Margin=new Thickness(0,6,0,2)});var box=new TextBox{Padding=new Thickness(6),MinHeight=30,AcceptsReturn=multi,TextWrapping=multi?TextWrapping.Wrap:TextWrapping.NoWrap};if(multi)box.Height=60;box.SetBinding(TextBox.TextProperty,new Binding(path){UpdateSourceTrigger=UpdateSourceTrigger.PropertyChanged,TargetNullValue=""});p.Children.Add(box);}static void AddCheck(Panel p,string label,string path){var c=new CheckBox{Content=label,Margin=new Thickness(0,8,0,2)};c.SetBinding(CheckBox.IsCheckedProperty,path);p.Children.Add(c);}static void AddCombo(Panel p,string label,string path,Array values){p.Children.Add(new TextBlock{Text=label,Margin=new Thickness(0,6,0,2)});var c=new ComboBox{ItemsSource=values,Padding=new Thickness(5)};c.SetBinding(ComboBox.SelectedItemProperty,path);p.Children.Add(c);}
 void Save(object sender,RoutedEventArgs e){var v=ServerValidator.Validate(server,all,paths.Resolve);if(!v.IsValid){errors.Text=string.Join(Environment.NewLine,v.Errors);return;}DialogResult=true;}
}
public sealed class SettingsWindow:Window
{
 public SettingsWindow(GlobalSettings settings){Title="Settings";Width=500;Height=530;WindowStartupLocation=WindowStartupLocation.CenterOwner;DataContext=settings;var root=new DockPanel{Margin=new Thickness(18)};var buttons=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right};var ok=new Button{Content="Save",Padding=new Thickness(14,7,14,7),Margin=new Thickness(5)};ok.Click+=(_,_)=>DialogResult=true;var cancel=new Button{Content="Cancel",Padding=new Thickness(14,7,14,7),Margin=new Thickness(5)};cancel.Click+=(_,_)=>DialogResult=false;buttons.Children.Add(ok);buttons.Children.Add(cancel);DockPanel.SetDock(buttons,Dock.Bottom);root.Children.Add(buttons);var p=new StackPanel();Add(p,"Logging root directory",nameof(settings.LoggingRootDirectory));Add(p,"Monitoring interval (seconds)",nameof(settings.MonitoringIntervalSeconds));Add(p,"Default graceful stop timeout",nameof(settings.DefaultGracefulStopTimeoutSeconds));Add(p,"Maximum log lines",nameof(settings.MaximumLogLines));Check(p,"Default force-kill policy",nameof(settings.DefaultForceKillPolicy));Check(p,"Confirm before force kill",nameof(settings.ConfirmForceKill));Check(p,"Auto-start enabled servers",nameof(settings.AutoStartEnabledServers));root.Children.Add(p);Content=root;}
 static void Add(Panel p,string label,string path){p.Children.Add(new TextBlock{Text=label,Margin=new Thickness(0,9,0,2)});var b=new TextBox{Padding=new Thickness(6)};b.SetBinding(TextBox.TextProperty,new Binding(path){UpdateSourceTrigger=UpdateSourceTrigger.PropertyChanged});p.Children.Add(b);}static void Check(Panel p,string label,string path){var c=new CheckBox{Content=label,Margin=new Thickness(0,12,0,0)};c.SetBinding(CheckBox.IsCheckedProperty,path);p.Children.Add(c);}
}
