using MessagingServerManager.Core;using MessagingServerManager.Infrastructure;using MessagingServerManager.ServerAdapters;
namespace MessagingServerManager.Core.Tests;
public class CoreTests
{
 [Fact]public void Validation_detects_duplicate_names_and_ports(){var a=new ServerDefinition{Name="A",Nats=new(){ClientPort=4222,MonitoringPort=8222}};var b=new ServerDefinition{Name="A",Nats=new(){ClientPort=4222,MonitoringPort=8223}};var result=ServerValidator.Validate(b,[a,b],Path.GetFullPath);Assert.Contains(result.Errors,x=>x.Contains("unique"));Assert.Contains(result.Errors,x=>x.Contains("4222"));}
 [Fact]public void Cpu_usage_uses_cpu_wall_and_core_deltas()=>Assert.Equal(25,CpuUsageCalculator.Calculate(TimeSpan.FromSeconds(1),TimeSpan.FromSeconds(2),2));
 [Fact]public void Nats_config_mode_quotes_resolved_path(){var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString());var adapter=new NatsServerAdapter(new(root),new());var d=new ServerDefinition{LaunchMode=LaunchMode.ConfigFile,ConfigFilePath="a file.conf"};Assert.Contains($"-c \"{Path.Combine(root,"a file.conf")}\"",adapter.BuildArguments(d));}
 [Fact]public void Tibco_managed_options_generates_ports(){var adapter=new TibRvServerAdapter(new(Path.GetTempPath()),new());var d=new ServerDefinition{ServerType=ServerType.TibcoRendezvous,TibRv=new(){Service=7500,HttpAdministrationPort=7580}};Assert.Contains("-service 7500",adapter.BuildArguments(d));Assert.Contains("-http 7580",adapter.BuildArguments(d));}
 [Fact]public void Nats_managed_options_include_configured_log_root(){var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString());var adapter=new NatsServerAdapter(new(root),new());var d=new ServerDefinition{LogFilePath="nats/server.log",Nats=new(){ClientPort=4222,MonitoringPort=8222}};var args=adapter.BuildArguments(d,new GlobalSettings{LoggingRootDirectory="my-logs"});Assert.Contains($"--log \"{Path.Combine(root,"my-logs","nats","server.log")}\"",args);}
 [Fact]public void Validation_rejects_internal_duplicate_ports_and_negative_timeouts(){var d=new ServerDefinition{Nats=new(){ClientPort=4222,MonitoringPort=4222},GracefulStopTimeoutSeconds=-1,HealthCheckGracePeriodSeconds=-1};var result=ServerValidator.Validate(d,[d],Path.GetFullPath);Assert.Contains(result.Errors,x=>x.Contains("unique"));Assert.Contains(result.Errors,x=>x.Contains("timeout"));Assert.Contains(result.Errors,x=>x.Contains("grace period"));}
 [Fact]public void Remote_nats_does_not_require_local_executable(){var d=new ServerDefinition{Location=ServerLocation.Remote,Executable="",HealthCheckHost="nats.example",Nats=new(){ClientPort=4222,MonitoringPort=8222}};Assert.True(ServerValidator.Validate(d,[d],Path.GetFullPath).IsValid);}
 [Fact]public void Nats_tls_managed_options_use_https_and_certificate_flags(){var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString());var adapter=new NatsServerAdapter(new(root),new());var d=new ServerDefinition{LaunchMode=LaunchMode.ManagedOptions,Nats=new(){UseTls=true,ClientPort=4222,MonitoringPort=8222,TlsCertificatePath="server.pem",TlsPrivateKeyPath="server-key.pem",TlsCaCertificatePath="ca.pem",TlsVerifyClients=true}};var args=adapter.BuildArguments(d);Assert.Contains("--https_port 8222",args);Assert.DoesNotContain("--http_port",args);Assert.Contains("--tls ",args);Assert.Contains("--tlscert",args);Assert.Contains("--tlskey",args);Assert.Contains("--tlscacert",args);Assert.Contains("--tlsverify",args);}
 [Fact]public void Remote_tls_monitoring_builds_https_varz_endpoint(){var d=new ServerDefinition{Location=ServerLocation.Remote,HealthCheckHost="nats.example",Nats=new(){UseTls=true,MonitoringPort=8443}};Assert.Equal("https://nats.example:8443/varz",NatsServerAdapter.GetMonitoringUri(d).AbsoluteUri.TrimEnd('/'));}
}
