using MessagingServerManager.Core;using MessagingServerManager.Infrastructure;using MessagingServerManager.ServerAdapters;
namespace MessagingServerManager.Core.Tests;
public class CoreTests
{
 [Fact]public void Validation_detects_duplicate_names_and_ports(){var a=new ServerDefinition{Name="A",Nats=new(){ClientPort=4222,MonitoringPort=8222}};var b=new ServerDefinition{Name="A",Nats=new(){ClientPort=4222,MonitoringPort=8223}};var result=ServerValidator.Validate(b,[a,b],Path.GetFullPath);Assert.Contains(result.Errors,x=>x.Contains("unique"));Assert.Contains(result.Errors,x=>x.Contains("4222"));}
 [Fact]public void Cpu_usage_uses_cpu_wall_and_core_deltas()=>Assert.Equal(25,CpuUsageCalculator.Calculate(TimeSpan.FromSeconds(1),TimeSpan.FromSeconds(2),2));
 [Fact]public void Nats_config_mode_quotes_resolved_path(){var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString());var adapter=new NatsServerAdapter(new(root),new());var d=new ServerDefinition{LaunchMode=LaunchMode.ConfigFile,ConfigFilePath="a file.conf"};Assert.Contains($"-c \"{Path.Combine(root,"a file.conf")}\"",adapter.BuildArguments(d));}
 [Fact]public async Task Managed_nats_config_is_created_with_absolute_log_and_64mb_payload(){var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));try{var adapter=new NatsServerAdapter(new(root),new());var d=new ServerDefinition{LaunchMode=LaunchMode.ConfigFile,ManageConfigFile=true,ConfigFilePath="generated/nats.conf",LogFilePath="nats/server.log",Nats=new(){ClientPort=4222,MonitoringPort=8222,MaxPayloadBytes=64*1024*1024}};await adapter.PrepareAsync(d,new GlobalSettings{LoggingRootDirectory="logs"},default);var config=await File.ReadAllTextAsync(Path.Combine(root,"generated","nats.conf"));Assert.Contains("max_payload: 67108864",config);Assert.Contains("log_file:",config);Assert.Contains(Path.Combine(root,"logs","nats","server.log").Replace("\\","\\\\"),config);Assert.True(Directory.Exists(Path.Combine(root,"logs","nats")));}finally{if(Directory.Exists(root))Directory.Delete(root,true);}}
 [Fact]public async Task External_nats_config_uses_config_directory_and_creates_relative_log_folder(){var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));try{var config=Path.Combine(root,"config","nats.conf");Directory.CreateDirectory(Path.GetDirectoryName(config)!);await File.WriteAllTextAsync(config,"port: 4222\nlog_file: logs/server.log\n");var adapter=new NatsServerAdapter(new(root),new());var d=new ServerDefinition{LaunchMode=LaunchMode.ConfigFile,ConfigFilePath=config,ManageConfigFile=false};await adapter.PrepareAsync(d,new GlobalSettings(),default);var start=adapter.BuildStartInfo(d,new GlobalSettings());Assert.Equal(Path.GetDirectoryName(config),start.WorkingDirectory);Assert.True(Directory.Exists(Path.Combine(root,"config","logs")));}finally{if(Directory.Exists(root))Directory.Delete(root,true);}}
 [Fact]public void Tibco_managed_options_generates_production_command_line(){var adapter=new TibRvServerAdapter(new(Path.GetTempPath()),new());var d=new ServerDefinition{ServerType=ServerType.TibcoRendezvous,TibRv=new(){Service=7500,ListenHost="localhost",HttpAdministrationHost="localhost",HttpAdministrationPort=7580,ReliabilitySeconds=60}};var args=adapter.BuildArguments(d);Assert.Contains("-listen localhost:7500",args);Assert.Contains("-reliability 60",args);Assert.Contains("-http localhost:7580",args);Assert.Contains("-reuse-port 7500",args);}
 [Fact]public void Nats_managed_options_include_configured_log_root(){var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString());var adapter=new NatsServerAdapter(new(root),new());var d=new ServerDefinition{LogFilePath="nats/server.log",Nats=new(){ClientPort=4222,MonitoringPort=8222}};var args=adapter.BuildArguments(d,new GlobalSettings{LoggingRootDirectory="my-logs"});Assert.Contains($"--log \"{Path.Combine(root,"my-logs","nats","server.log")}\"",args);}
 [Fact]public void Validation_rejects_internal_duplicate_ports_and_negative_timeouts(){var d=new ServerDefinition{Nats=new(){ClientPort=4222,MonitoringPort=4222},GracefulStopTimeoutSeconds=-1,HealthCheckGracePeriodSeconds=-1};var result=ServerValidator.Validate(d,[d],Path.GetFullPath);Assert.Contains(result.Errors,x=>x.Contains("unique"));Assert.Contains(result.Errors,x=>x.Contains("timeout"));Assert.Contains(result.Errors,x=>x.Contains("grace period"));}
 [Fact]public void Remote_nats_does_not_require_local_executable(){var d=new ServerDefinition{Location=ServerLocation.Remote,Executable="",HealthCheckHost="nats.example",Nats=new(){ClientPort=4222,MonitoringPort=8222}};Assert.True(ServerValidator.Validate(d,[d],Path.GetFullPath).IsValid);}
 [Fact]public void Managed_config_allows_a_new_path_but_external_config_requires_a_file(){var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));var managed=new ServerDefinition{LaunchMode=LaunchMode.ConfigFile,ManageConfigFile=true,ConfigFilePath=Path.Combine(root,"new.conf")};var external=managed.Clone();external.Id=Guid.NewGuid();external.Name="External";external.ManageConfigFile=false;Assert.True(ServerValidator.Validate(managed,[managed],Path.GetFullPath).IsValid);Assert.Contains(ServerValidator.Validate(external,[external],Path.GetFullPath).Errors,x=>x.Contains("externally managed"));}
 [Fact]public void Remote_tibco_with_http_metrics_is_valid(){var d=new ServerDefinition{Location=ServerLocation.Remote,ServerType=ServerType.TibcoRendezvous,Executable="",HealthCheckHost="rv.example",TibRv=new(){Service=7500,HttpAdministrationPort=7580}};Assert.True(ServerValidator.Validate(d,[d],Path.GetFullPath).IsValid);}
 [Fact]public void Nats_tls_managed_options_use_https_and_certificate_flags(){var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString());var adapter=new NatsServerAdapter(new(root),new());var d=new ServerDefinition{LaunchMode=LaunchMode.ManagedOptions,Nats=new(){UseTls=true,ClientPort=4222,MonitoringPort=8222,TlsCertificatePath="server.pem",TlsPrivateKeyPath="server-key.pem",TlsCaCertificatePath="ca.pem",TlsVerifyClients=true}};var args=adapter.BuildArguments(d);Assert.Contains("--https_port 8222",args);Assert.DoesNotContain("--http_port",args);Assert.Contains("--tls ",args);Assert.Contains("--tlscert",args);Assert.Contains("--tlskey",args);Assert.Contains("--tlscacert",args);Assert.Contains("--tlsverify",args);}
 [Fact]public void Remote_tls_monitoring_builds_https_varz_endpoint(){var d=new ServerDefinition{Location=ServerLocation.Remote,HealthCheckHost="nats.example",Nats=new(){UseTls=true,MonitoringPort=8443}};Assert.Equal("https://nats.example:8443/varz",NatsServerAdapter.GetMonitoringUri(d).AbsoluteUri.TrimEnd('/'));}
 [Fact]public void Tibco_prometheus_metrics_are_parsed_and_aggregated(){var text="""
 # HELP rv_service_uptime Number of seconds uptime
 rv_service_uptime{component="rvd",version="8.7.0",host="rv01",service="7500",network="239.1.1.1"} 125
 rv_service_client_connections{component="rvd",version="8.7.0",host="rv01",service="7500",network="239.1.1.1"} 3
 rv_service_subscriptions{component="rvd",version="8.7.0",host="rv01",service="7500",network="239.1.1.1"} 12
 rv_service_inbound_messages_total{component="rvd",version="8.7.0",host="rv01",service="7500",network="239.1.1.1"} 42
 rv_service_outbound_messages_total{component="rvd",version="8.7.0",host="rv01",service="7500",network="239.1.1.1"} 40
 rv_service_packets_missed_total{component="rvd",version="8.7.0",host="rv01",service="7500",network="239.1.1.1"} 2
 """;var metrics=TibRvServerAdapter.ParseMetrics(text);Assert.Equal(TimeSpan.FromSeconds(125),metrics.Uptime);Assert.Equal(3,metrics.ClientConnections);Assert.Equal(12,metrics.Subscriptions);Assert.Equal(42,metrics.InMessages);Assert.Equal(2,metrics.MissedPackets);Assert.Equal("rvd",metrics.Component);Assert.Equal("8.7.0",metrics.Version);Assert.Equal("rv01",metrics.Host);}
 [Fact]public void Tibco_metrics_select_configured_label_series(){var text="""
 rv_service_client_connections{component="rvd",service="7500",network="net-a"} 3
 rv_service_inbound_messages_total{component="rvd",service="7500",network="net-a"} 42
 rv_service_client_connections{component="rvd",service="7600",network="net-b"} 9
 rv_service_inbound_messages_total{component="rvd",service="7600",network="net-b"} 100
 """;var metrics=TibRvServerAdapter.ParseMetrics(text,"7500","net-a");Assert.Equal(3,metrics.ClientConnections);Assert.Equal(42,metrics.InMessages);Assert.Equal("7500",metrics.Service);Assert.Equal("net-a",metrics.Network);}
 [Fact]public void Tibco_metrics_reject_a_missing_configured_series(){const string text="rv_service_client_connections{service=\"7600\",network=\"net-b\"} 9";Assert.Throws<InvalidDataException>(()=>TibRvServerAdapter.ParseMetrics(text,"7500","net-a"));}
 [Fact]public void Tibco_fixture_keeps_services_separate(){var text=File.ReadAllText(Path.Combine(AppContext.BaseDirectory,"Fixtures","tibrv-multi-service.prom"));var first=TibRvServerAdapter.ParseMetrics(text,"7500","net-a");var second=TibRvServerAdapter.ParseMetrics(text,"7600","net-b");Assert.Equal(3,first.ClientConnections);Assert.Equal(42,first.InMessages);Assert.Equal(9,second.ClientConnections);Assert.Equal(100,second.InMessages);}
}
